name: 'setup-terragrunt'
description: 'Setup Terragrunt CLI for GitHub Actions'
author: 'Docktape Ltd.'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  version:
    description: 'The version of Terragrunt CLI to install. Defaults to v0.58.9'
    default: v0.58.9
    required: false

runs:
  using: node20
  main: dist/index.js
