name: Continuous Integration

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  simple-setup-terragrunt:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terragrunt
        uses: ./

      - name: Terragrunt version
        run: terragrunt -version

  version-setup-terragrunt:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terragrunt
        uses: ./
        with:
          version: v0.58.8

      - name: Terragrunt version
        run: terragrunt -version
